replicaCount: 2
image:
  repository: mita-backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: true
  className: nginx
  host: mita.example.com
  tls: true
redisUrl: redis://redis:6379/0
postgresUrl: postgres://postgres:postgres@db:5432/mita
