apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pg-backup
              image: python:3.11-slim
              command: ["python", "/scripts/backup_database.py"]
              env:
                - name: DATABASE_URL
                  value: {{ .Values.postgresUrl | quote }}
                - name: S3_BUCKET
                  value: {{ .Values.backupBucket | quote }}
              volumeMounts:
                - name: script
                  mountPath: /scripts
          restartPolicy: OnFailure
          volumes:
            - name: script
              configMap:
                name: pg-backup-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-backup-script
data:
  backup_database.py: |
{{ .Files.Get "../../scripts/backup_database.py" | indent 4 }}
