currency: USD
mandatory_categories: [housing, utilities, healthcare, debts, insurance]
seasonal_factors:
  winter:
    utilities: 1.2
    clothing: 1.15
  summer:
    travel: 1.3
    utilities: 0.9
classes:
  extremely_low:
    housing: 0.45
    food: 0.18
    transport: 0.12
    utilities: 0.05
    clothing: 0.02
    healthcare: 0.02
    entertainment: 0.01
    miscellaneous: 0.15
  middle:
    housing: 0.33
    food: 0.18
    transport: 0.17
    education: 0.12
    healthcare: 0.08
    savings: 0.10
    entertainment: 0.07
    miscellaneous: 0.05
  high:
    investments: 0.40
    luxury: 0.20
    education: 0.15
    philanthropy: 0.10
    travel: 0.05