name: mita
description: Money Intelligence Task Assistant — MITA frontend onboarding
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0                   # HTTP client
  flutter_secure_storage: ^8.0.0  # Secure token storage
  intl: ^0.18.1
  google_sign_in: ^6.1.5
  fl_chart: ^0.71.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/mitalogo.png
    - assets/fonts/
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/static/Sora-Regular.ttf
        - asset: assets/fonts/Sora/static/Sora-Bold.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/static/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope/static/Manrope-Bold.ttf
