name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fail on Cyrillic characters
      run: |
        if grep -rIn --exclude-dir=.git --exclude-dir=docs/legacy -P "[\p{Cyrillic}]" .; then
          echo "Cyrillic characters detected"
          exit 1
        fi

    - name: Run tests
      run: |
        export PYTHONPATH=.
        pytest
