name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint & style
        run: |
          black --check .
          isort --check .
          ruff .

      - name: Fail on Cyrillic characters
        run: |
          if grep -rIn --exclude-dir=.git --exclude-dir=docs/legacy -P "[\p{Cyrillic}]" .; then
            echo "Cyrillic characters detected"
            exit 1
          fi

      - name: Tests with coverage
        run: |
          export PYTHONPATH=.
          pytest --cov=app --cov-report=xml --cov-report=term --cov-fail-under=60

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: coverage.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/mita-backend:latest
